/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// LED1 address and mask defines
#pragma	ioport	LED1_Data_ADDR:	0x4
BYTE			LED1_Data_ADDR;
#pragma	ioport	LED1_DriveMode_0_ADDR:	0x104
BYTE			LED1_DriveMode_0_ADDR;
#pragma	ioport	LED1_DriveMode_1_ADDR:	0x105
BYTE			LED1_DriveMode_1_ADDR;
#pragma	ioport	LED1_DriveMode_2_ADDR:	0x7
BYTE			LED1_DriveMode_2_ADDR;
#pragma	ioport	LED1_GlobalSelect_ADDR:	0x6
BYTE			LED1_GlobalSelect_ADDR;
#pragma	ioport	LED1_IntCtrl_0_ADDR:	0x106
BYTE			LED1_IntCtrl_0_ADDR;
#pragma	ioport	LED1_IntCtrl_1_ADDR:	0x107
BYTE			LED1_IntCtrl_1_ADDR;
#pragma	ioport	LED1_IntEn_ADDR:	0x5
BYTE			LED1_IntEn_ADDR;
#define LED1_MASK 0x1
// LED2 address and mask defines
#pragma	ioport	LED2_Data_ADDR:	0x4
BYTE			LED2_Data_ADDR;
#pragma	ioport	LED2_DriveMode_0_ADDR:	0x104
BYTE			LED2_DriveMode_0_ADDR;
#pragma	ioport	LED2_DriveMode_1_ADDR:	0x105
BYTE			LED2_DriveMode_1_ADDR;
#pragma	ioport	LED2_DriveMode_2_ADDR:	0x7
BYTE			LED2_DriveMode_2_ADDR;
#pragma	ioport	LED2_GlobalSelect_ADDR:	0x6
BYTE			LED2_GlobalSelect_ADDR;
#pragma	ioport	LED2_IntCtrl_0_ADDR:	0x106
BYTE			LED2_IntCtrl_0_ADDR;
#pragma	ioport	LED2_IntCtrl_1_ADDR:	0x107
BYTE			LED2_IntCtrl_1_ADDR;
#pragma	ioport	LED2_IntEn_ADDR:	0x5
BYTE			LED2_IntEn_ADDR;
#define LED2_MASK 0x2
// SW1 address and mask defines
#pragma	ioport	SW1_Data_ADDR:	0x4
BYTE			SW1_Data_ADDR;
#pragma	ioport	SW1_DriveMode_0_ADDR:	0x104
BYTE			SW1_DriveMode_0_ADDR;
#pragma	ioport	SW1_DriveMode_1_ADDR:	0x105
BYTE			SW1_DriveMode_1_ADDR;
#pragma	ioport	SW1_DriveMode_2_ADDR:	0x7
BYTE			SW1_DriveMode_2_ADDR;
#pragma	ioport	SW1_GlobalSelect_ADDR:	0x6
BYTE			SW1_GlobalSelect_ADDR;
#pragma	ioport	SW1_IntCtrl_0_ADDR:	0x106
BYTE			SW1_IntCtrl_0_ADDR;
#pragma	ioport	SW1_IntCtrl_1_ADDR:	0x107
BYTE			SW1_IntCtrl_1_ADDR;
#pragma	ioport	SW1_IntEn_ADDR:	0x5
BYTE			SW1_IntEn_ADDR;
#define SW1_MASK 0x10
// SW2 address and mask defines
#pragma	ioport	SW2_Data_ADDR:	0x4
BYTE			SW2_Data_ADDR;
#pragma	ioport	SW2_DriveMode_0_ADDR:	0x104
BYTE			SW2_DriveMode_0_ADDR;
#pragma	ioport	SW2_DriveMode_1_ADDR:	0x105
BYTE			SW2_DriveMode_1_ADDR;
#pragma	ioport	SW2_DriveMode_2_ADDR:	0x7
BYTE			SW2_DriveMode_2_ADDR;
#pragma	ioport	SW2_GlobalSelect_ADDR:	0x6
BYTE			SW2_GlobalSelect_ADDR;
#pragma	ioport	SW2_IntCtrl_0_ADDR:	0x106
BYTE			SW2_IntCtrl_0_ADDR;
#pragma	ioport	SW2_IntCtrl_1_ADDR:	0x107
BYTE			SW2_IntCtrl_1_ADDR;
#pragma	ioport	SW2_IntEn_ADDR:	0x5
BYTE			SW2_IntEn_ADDR;
#define SW2_MASK 0x20
