//*****************************************************************************
//*****************************************************************************
//  FILENAME: Counter24.h
//   Version: 2.5, Updated on 2014/7/14 at 8:8:54
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: Counter24 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2014. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Counter24_INCLUDE
#define Counter24_INCLUDE

#include <m8c.h>

#pragma fastcall16 Counter24_EnableInt
#pragma fastcall16 Counter24_DisableInt
#pragma fastcall16 Counter24_Start
#pragma fastcall16 Counter24_Stop
#pragma fastcall16 Counter24_ReadCounter              // Read  DR0
#pragma fastcall16 Counter24_WritePeriod              // Write DR1
#pragma fastcall16 Counter24_ReadCompareValue         // Read  DR2
#pragma fastcall16 Counter24_WriteCompareValue        // Write DR2


//-------------------------------------------------
// Prototypes of the Counter24 API.
//-------------------------------------------------
                                                                           
extern void Counter24_EnableInt(void);                           // Proxy Class 1
extern void Counter24_DisableInt(void);                          // Proxy Class 1
extern void Counter24_Start(void);                               // Proxy Class 1
extern void Counter24_Stop(void);                                // Proxy Class 1
extern void Counter24_ReadCounter(DWORD * pdwCount);             // Proxy Class 3
extern void Counter24_WritePeriod(DWORD dwPeriod);               // Proxy Class 2
extern void Counter24_ReadCompareValue(DWORD * pdwCompareValue); // Proxy Class 3
extern void Counter24_WriteCompareValue(DWORD dwCompareValue);   // Proxy Class 2


//--------------------------------------------------
// Constants for Counter24 API's.
//--------------------------------------------------

#define Counter24_CONTROL_REG_START_BIT        ( 0x01 )
#define Counter24_INT_REG_ADDR                 ( 0x0e1 )
#define Counter24_INT_MASK                     ( 0x40 )


//--------------------------------------------------
// Constants for Counter24 user defined values
//--------------------------------------------------

#define Counter24_PERIOD                       ( 0x12c7b )
#define Counter24_COMPARE_VALUE                ( 0x12c7a )


//-------------------------------------------------
// Register Addresses for Counter24
//-------------------------------------------------

#pragma ioport  Counter24_COUNTER_LSB_REG:  0x030          //Count register LSB
BYTE            Counter24_COUNTER_LSB_REG;
#pragma ioport  Counter24_COUNTER_ISB_REG:  0x034          //Count register ISB
BYTE            Counter24_COUNTER_ISB_REG;
#pragma ioport  Counter24_COUNTER_MSB_REG:  0x038          //Count register MSB
BYTE            Counter24_COUNTER_MSB_REG;
#pragma ioport  Counter24_PERIOD_LSB_REG:   0x031          //Period register LSB
BYTE            Counter24_PERIOD_LSB_REG;
#pragma ioport  Counter24_PERIOD_ISB_REG:   0x035          //Period register ISB
BYTE            Counter24_PERIOD_ISB_REG;
#pragma ioport  Counter24_PERIOD_MSB_REG:   0x039          //Period register MSB
BYTE            Counter24_PERIOD_MSB_REG;
#pragma ioport  Counter24_COMPARE_LSB_REG:  0x032          //Compare register LSB
BYTE            Counter24_COMPARE_LSB_REG;
#pragma ioport  Counter24_COMPARE_ISB_REG:  0x036          //Compare register ISB
BYTE            Counter24_COMPARE_ISB_REG;
#pragma ioport  Counter24_COMPARE_MSB_REG:  0x03a          //Compare register MSB
BYTE            Counter24_COMPARE_MSB_REG;
#pragma ioport  Counter24_CONTROL_LSB_REG:  0x033          //Control register LSB
BYTE            Counter24_CONTROL_LSB_REG;
#pragma ioport  Counter24_CONTROL_ISB_REG:  0x037          //Control register ISB
BYTE            Counter24_CONTROL_ISB_REG;
#pragma ioport  Counter24_CONTROL_MSB_REG:  0x03b          //Control register MSB
BYTE            Counter24_CONTROL_MSB_REG;
#pragma ioport  Counter24_FUNC_LSB_REG: 0x130              //Function register LSB
BYTE            Counter24_FUNC_LSB_REG;
#pragma ioport  Counter24_FUNC_ISB_REG: 0x134              //Function register ISB
BYTE            Counter24_FUNC_ISB_REG;
#pragma ioport  Counter24_FUNC_MSB_REG: 0x138              //Function register MSB
BYTE            Counter24_FUNC_MSB_REG;
#pragma ioport  Counter24_INPUT_LSB_REG:    0x131          //Input register LSB
BYTE            Counter24_INPUT_LSB_REG;
#pragma ioport  Counter24_INPUT_ISB_REG:    0x135          //Input register ISB
BYTE            Counter24_INPUT_ISB_REG;
#pragma ioport  Counter24_INPUT_MSB_REG:    0x139          //Input register MSB
BYTE            Counter24_INPUT_MSB_REG;
#pragma ioport  Counter24_OUTPUT_LSB_REG:   0x132          //Output register LSB
BYTE            Counter24_OUTPUT_LSB_REG;
#pragma ioport  Counter24_OUTPUT_ISB_REG:   0x136          //Output register ISB
BYTE            Counter24_OUTPUT_ISB_REG;
#pragma ioport  Counter24_OUTPUT_MSB_REG:   0x13a          //Output register MSB
BYTE            Counter24_OUTPUT_MSB_REG;
#pragma ioport  Counter24_INT_REG:       0x0e1             //Interrupt Mask Register
BYTE            Counter24_INT_REG;


//-------------------------------------------------
// Counter24 Macro 'Functions'
//-------------------------------------------------

#define Counter24_Start_M \
   ( Counter24_CONTROL_LSB_REG |=  Counter24_CONTROL_REG_START_BIT )

#define Counter24_Stop_M  \
   ( Counter24_CONTROL_LSB_REG &= ~Counter24_CONTROL_REG_START_BIT )

#define Counter24_EnableInt_M   \
   M8C_EnableIntMask(  Counter24_INT_REG, Counter24_INT_MASK )

#define Counter24_DisableInt_M  \
   M8C_DisableIntMask( Counter24_INT_REG, Counter24_INT_MASK )

#endif
// end of file Counter24.h
