//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWMPiano1.h
//   Version: 2.5, Updated on 2013/5/19 at 10:44:6
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWMPiano1_INCLUDE
#define PWMPiano1_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWMPiano1_EnableInt
#pragma fastcall16 PWMPiano1_DisableInt
#pragma fastcall16 PWMPiano1_Start
#pragma fastcall16 PWMPiano1_Stop
#pragma fastcall16 PWMPiano1_wReadCounter              // Read  DR0
#pragma fastcall16 PWMPiano1_WritePeriod               // Write DR1
#pragma fastcall16 PWMPiano1_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWMPiano1_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWMPiano1_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWMPiano1_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWMPiano1 API.
//-------------------------------------------------

extern void PWMPiano1_EnableInt(void);                  // Proxy Class 1
extern void PWMPiano1_DisableInt(void);                 // Proxy Class 1
extern void PWMPiano1_Start(void);                      // Proxy Class 1
extern void PWMPiano1_Stop(void);                       // Proxy Class 1
extern WORD PWMPiano1_wReadCounter(void);               // Proxy Class 2
extern void PWMPiano1_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWMPiano1_wReadPulseWidth(void);            // Proxy Class 1
extern void PWMPiano1_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWMPiano1_ReadCounter(void);            // Deprecated
extern WORD wPWMPiano1_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWMPiano1 API's.
//-------------------------------------------------

#define PWMPiano1_CONTROL_REG_START_BIT        ( 0x01 )
#define PWMPiano1_INT_REG_ADDR                 ( 0x0df )
#define PWMPiano1_INT_MASK                     ( 0x08 )


//--------------------------------------------------
// Constants for PWMPiano1 user defined values
//--------------------------------------------------

#define PWMPiano1_PERIOD                       ( 0x0 )
#define PWMPiano1_PULSE_WIDTH                  ( 0x0 )


//-------------------------------------------------
// Register Addresses for PWMPiano1
//-------------------------------------------------

#pragma ioport  PWMPiano1_COUNTER_LSB_REG:  0x048          //DR0 Count register LSB
BYTE            PWMPiano1_COUNTER_LSB_REG;
#pragma ioport  PWMPiano1_COUNTER_MSB_REG:  0x04c          //DR0 Count register MSB
BYTE            PWMPiano1_COUNTER_MSB_REG;
#pragma ioport  PWMPiano1_PERIOD_LSB_REG:   0x049          //DR1 Period register LSB
BYTE            PWMPiano1_PERIOD_LSB_REG;
#pragma ioport  PWMPiano1_PERIOD_MSB_REG:   0x04d          //DR1 Period register MSB
BYTE            PWMPiano1_PERIOD_MSB_REG;
#pragma ioport  PWMPiano1_COMPARE_LSB_REG:  0x04a          //DR2 Compare register LSB
BYTE            PWMPiano1_COMPARE_LSB_REG;
#pragma ioport  PWMPiano1_COMPARE_MSB_REG:  0x04e          //DR2 Compare register MSB
BYTE            PWMPiano1_COMPARE_MSB_REG;
#pragma ioport  PWMPiano1_CONTROL_LSB_REG:  0x04b          //Control register LSB
BYTE            PWMPiano1_CONTROL_LSB_REG;
#pragma ioport  PWMPiano1_CONTROL_MSB_REG:  0x04f          //Control register MSB
BYTE            PWMPiano1_CONTROL_MSB_REG;
#pragma ioport  PWMPiano1_FUNC_LSB_REG: 0x148              //Function register LSB
BYTE            PWMPiano1_FUNC_LSB_REG;
#pragma ioport  PWMPiano1_FUNC_MSB_REG: 0x14c              //Function register MSB
BYTE            PWMPiano1_FUNC_MSB_REG;
#pragma ioport  PWMPiano1_INPUT_LSB_REG:    0x149          //Input register LSB
BYTE            PWMPiano1_INPUT_LSB_REG;
#pragma ioport  PWMPiano1_INPUT_MSB_REG:    0x14d          //Input register MSB
BYTE            PWMPiano1_INPUT_MSB_REG;
#pragma ioport  PWMPiano1_OUTPUT_LSB_REG:   0x14a          //Output register LSB
BYTE            PWMPiano1_OUTPUT_LSB_REG;
#pragma ioport  PWMPiano1_OUTPUT_MSB_REG:   0x14e          //Output register MSB
BYTE            PWMPiano1_OUTPUT_MSB_REG;
#pragma ioport  PWMPiano1_INT_REG:       0x0df             //Interrupt Mask Register
BYTE            PWMPiano1_INT_REG;


//-------------------------------------------------
// PWMPiano1 Macro 'Functions'
//-------------------------------------------------

#define PWMPiano1_Start_M \
   ( PWMPiano1_CONTROL_LSB_REG |=  PWMPiano1_CONTROL_REG_START_BIT )

#define PWMPiano1_Stop_M  \
   ( PWMPiano1_CONTROL_LSB_REG &= ~PWMPiano1_CONTROL_REG_START_BIT )

#define PWMPiano1_EnableInt_M   \
   M8C_EnableIntMask(  PWMPiano1_INT_REG, PWMPiano1_INT_MASK )

#define PWMPiano1_DisableInt_M  \
   M8C_DisableIntMask( PWMPiano1_INT_REG, PWMPiano1_INT_MASK )

#endif
// end of file PWMPiano1.h
