//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWMPiano3.h
//   Version: 2.5, Updated on 2013/5/19 at 10:44:6
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWMPiano3_INCLUDE
#define PWMPiano3_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWMPiano3_EnableInt
#pragma fastcall16 PWMPiano3_DisableInt
#pragma fastcall16 PWMPiano3_Start
#pragma fastcall16 PWMPiano3_Stop
#pragma fastcall16 PWMPiano3_wReadCounter              // Read  DR0
#pragma fastcall16 PWMPiano3_WritePeriod               // Write DR1
#pragma fastcall16 PWMPiano3_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWMPiano3_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWMPiano3_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWMPiano3_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWMPiano3 API.
//-------------------------------------------------

extern void PWMPiano3_EnableInt(void);                  // Proxy Class 1
extern void PWMPiano3_DisableInt(void);                 // Proxy Class 1
extern void PWMPiano3_Start(void);                      // Proxy Class 1
extern void PWMPiano3_Stop(void);                       // Proxy Class 1
extern WORD PWMPiano3_wReadCounter(void);               // Proxy Class 2
extern void PWMPiano3_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWMPiano3_wReadPulseWidth(void);            // Proxy Class 1
extern void PWMPiano3_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWMPiano3_ReadCounter(void);            // Deprecated
extern WORD wPWMPiano3_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWMPiano3 API's.
//-------------------------------------------------

#define PWMPiano3_CONTROL_REG_START_BIT        ( 0x01 )
#define PWMPiano3_INT_REG_ADDR                 ( 0x0e1 )
#define PWMPiano3_INT_MASK                     ( 0x08 )


//--------------------------------------------------
// Constants for PWMPiano3 user defined values
//--------------------------------------------------

#define PWMPiano3_PERIOD                       ( 0x0 )
#define PWMPiano3_PULSE_WIDTH                  ( 0x0 )


//-------------------------------------------------
// Register Addresses for PWMPiano3
//-------------------------------------------------

#pragma ioport  PWMPiano3_COUNTER_LSB_REG:  0x028          //DR0 Count register LSB
BYTE            PWMPiano3_COUNTER_LSB_REG;
#pragma ioport  PWMPiano3_COUNTER_MSB_REG:  0x02c          //DR0 Count register MSB
BYTE            PWMPiano3_COUNTER_MSB_REG;
#pragma ioport  PWMPiano3_PERIOD_LSB_REG:   0x029          //DR1 Period register LSB
BYTE            PWMPiano3_PERIOD_LSB_REG;
#pragma ioport  PWMPiano3_PERIOD_MSB_REG:   0x02d          //DR1 Period register MSB
BYTE            PWMPiano3_PERIOD_MSB_REG;
#pragma ioport  PWMPiano3_COMPARE_LSB_REG:  0x02a          //DR2 Compare register LSB
BYTE            PWMPiano3_COMPARE_LSB_REG;
#pragma ioport  PWMPiano3_COMPARE_MSB_REG:  0x02e          //DR2 Compare register MSB
BYTE            PWMPiano3_COMPARE_MSB_REG;
#pragma ioport  PWMPiano3_CONTROL_LSB_REG:  0x02b          //Control register LSB
BYTE            PWMPiano3_CONTROL_LSB_REG;
#pragma ioport  PWMPiano3_CONTROL_MSB_REG:  0x02f          //Control register MSB
BYTE            PWMPiano3_CONTROL_MSB_REG;
#pragma ioport  PWMPiano3_FUNC_LSB_REG: 0x128              //Function register LSB
BYTE            PWMPiano3_FUNC_LSB_REG;
#pragma ioport  PWMPiano3_FUNC_MSB_REG: 0x12c              //Function register MSB
BYTE            PWMPiano3_FUNC_MSB_REG;
#pragma ioport  PWMPiano3_INPUT_LSB_REG:    0x129          //Input register LSB
BYTE            PWMPiano3_INPUT_LSB_REG;
#pragma ioport  PWMPiano3_INPUT_MSB_REG:    0x12d          //Input register MSB
BYTE            PWMPiano3_INPUT_MSB_REG;
#pragma ioport  PWMPiano3_OUTPUT_LSB_REG:   0x12a          //Output register LSB
BYTE            PWMPiano3_OUTPUT_LSB_REG;
#pragma ioport  PWMPiano3_OUTPUT_MSB_REG:   0x12e          //Output register MSB
BYTE            PWMPiano3_OUTPUT_MSB_REG;
#pragma ioport  PWMPiano3_INT_REG:       0x0e1             //Interrupt Mask Register
BYTE            PWMPiano3_INT_REG;


//-------------------------------------------------
// PWMPiano3 Macro 'Functions'
//-------------------------------------------------

#define PWMPiano3_Start_M \
   ( PWMPiano3_CONTROL_LSB_REG |=  PWMPiano3_CONTROL_REG_START_BIT )

#define PWMPiano3_Stop_M  \
   ( PWMPiano3_CONTROL_LSB_REG &= ~PWMPiano3_CONTROL_REG_START_BIT )

#define PWMPiano3_EnableInt_M   \
   M8C_EnableIntMask(  PWMPiano3_INT_REG, PWMPiano3_INT_MASK )

#define PWMPiano3_DisableInt_M  \
   M8C_DisableIntMask( PWMPiano3_INT_REG, PWMPiano3_INT_MASK )

#endif
// end of file PWMPiano3.h
