/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// LED0 address and mask defines
#pragma	ioport	LED0_Data_ADDR:	0x0
BYTE			LED0_Data_ADDR;
#pragma	ioport	LED0_DriveMode_0_ADDR:	0x100
BYTE			LED0_DriveMode_0_ADDR;
#pragma	ioport	LED0_DriveMode_1_ADDR:	0x101
BYTE			LED0_DriveMode_1_ADDR;
#pragma	ioport	LED0_DriveMode_2_ADDR:	0x3
BYTE			LED0_DriveMode_2_ADDR;
#pragma	ioport	LED0_GlobalSelect_ADDR:	0x2
BYTE			LED0_GlobalSelect_ADDR;
#pragma	ioport	LED0_IntCtrl_0_ADDR:	0x102
BYTE			LED0_IntCtrl_0_ADDR;
#pragma	ioport	LED0_IntCtrl_1_ADDR:	0x103
BYTE			LED0_IntCtrl_1_ADDR;
#pragma	ioport	LED0_IntEn_ADDR:	0x1
BYTE			LED0_IntEn_ADDR;
#define LED0_MASK 0x1
// LED1 address and mask defines
#pragma	ioport	LED1_Data_ADDR:	0x0
BYTE			LED1_Data_ADDR;
#pragma	ioport	LED1_DriveMode_0_ADDR:	0x100
BYTE			LED1_DriveMode_0_ADDR;
#pragma	ioport	LED1_DriveMode_1_ADDR:	0x101
BYTE			LED1_DriveMode_1_ADDR;
#pragma	ioport	LED1_DriveMode_2_ADDR:	0x3
BYTE			LED1_DriveMode_2_ADDR;
#pragma	ioport	LED1_GlobalSelect_ADDR:	0x2
BYTE			LED1_GlobalSelect_ADDR;
#pragma	ioport	LED1_IntCtrl_0_ADDR:	0x102
BYTE			LED1_IntCtrl_0_ADDR;
#pragma	ioport	LED1_IntCtrl_1_ADDR:	0x103
BYTE			LED1_IntCtrl_1_ADDR;
#pragma	ioport	LED1_IntEn_ADDR:	0x1
BYTE			LED1_IntEn_ADDR;
#define LED1_MASK 0x2
// LED2 address and mask defines
#pragma	ioport	LED2_Data_ADDR:	0x0
BYTE			LED2_Data_ADDR;
#pragma	ioport	LED2_DriveMode_0_ADDR:	0x100
BYTE			LED2_DriveMode_0_ADDR;
#pragma	ioport	LED2_DriveMode_1_ADDR:	0x101
BYTE			LED2_DriveMode_1_ADDR;
#pragma	ioport	LED2_DriveMode_2_ADDR:	0x3
BYTE			LED2_DriveMode_2_ADDR;
#pragma	ioport	LED2_GlobalSelect_ADDR:	0x2
BYTE			LED2_GlobalSelect_ADDR;
#pragma	ioport	LED2_IntCtrl_0_ADDR:	0x102
BYTE			LED2_IntCtrl_0_ADDR;
#pragma	ioport	LED2_IntCtrl_1_ADDR:	0x103
BYTE			LED2_IntCtrl_1_ADDR;
#pragma	ioport	LED2_IntEn_ADDR:	0x1
BYTE			LED2_IntEn_ADDR;
#define LED2_MASK 0x4
// LED3 address and mask defines
#pragma	ioport	LED3_Data_ADDR:	0x0
BYTE			LED3_Data_ADDR;
#pragma	ioport	LED3_DriveMode_0_ADDR:	0x100
BYTE			LED3_DriveMode_0_ADDR;
#pragma	ioport	LED3_DriveMode_1_ADDR:	0x101
BYTE			LED3_DriveMode_1_ADDR;
#pragma	ioport	LED3_DriveMode_2_ADDR:	0x3
BYTE			LED3_DriveMode_2_ADDR;
#pragma	ioport	LED3_GlobalSelect_ADDR:	0x2
BYTE			LED3_GlobalSelect_ADDR;
#pragma	ioport	LED3_IntCtrl_0_ADDR:	0x102
BYTE			LED3_IntCtrl_0_ADDR;
#pragma	ioport	LED3_IntCtrl_1_ADDR:	0x103
BYTE			LED3_IntCtrl_1_ADDR;
#pragma	ioport	LED3_IntEn_ADDR:	0x1
BYTE			LED3_IntEn_ADDR;
#define LED3_MASK 0x8
// LED4 address and mask defines
#pragma	ioport	LED4_Data_ADDR:	0x0
BYTE			LED4_Data_ADDR;
#pragma	ioport	LED4_DriveMode_0_ADDR:	0x100
BYTE			LED4_DriveMode_0_ADDR;
#pragma	ioport	LED4_DriveMode_1_ADDR:	0x101
BYTE			LED4_DriveMode_1_ADDR;
#pragma	ioport	LED4_DriveMode_2_ADDR:	0x3
BYTE			LED4_DriveMode_2_ADDR;
#pragma	ioport	LED4_GlobalSelect_ADDR:	0x2
BYTE			LED4_GlobalSelect_ADDR;
#pragma	ioport	LED4_IntCtrl_0_ADDR:	0x102
BYTE			LED4_IntCtrl_0_ADDR;
#pragma	ioport	LED4_IntCtrl_1_ADDR:	0x103
BYTE			LED4_IntCtrl_1_ADDR;
#pragma	ioport	LED4_IntEn_ADDR:	0x1
BYTE			LED4_IntEn_ADDR;
#define LED4_MASK 0x10
// LED5 address and mask defines
#pragma	ioport	LED5_Data_ADDR:	0x0
BYTE			LED5_Data_ADDR;
#pragma	ioport	LED5_DriveMode_0_ADDR:	0x100
BYTE			LED5_DriveMode_0_ADDR;
#pragma	ioport	LED5_DriveMode_1_ADDR:	0x101
BYTE			LED5_DriveMode_1_ADDR;
#pragma	ioport	LED5_DriveMode_2_ADDR:	0x3
BYTE			LED5_DriveMode_2_ADDR;
#pragma	ioport	LED5_GlobalSelect_ADDR:	0x2
BYTE			LED5_GlobalSelect_ADDR;
#pragma	ioport	LED5_IntCtrl_0_ADDR:	0x102
BYTE			LED5_IntCtrl_0_ADDR;
#pragma	ioport	LED5_IntCtrl_1_ADDR:	0x103
BYTE			LED5_IntCtrl_1_ADDR;
#pragma	ioport	LED5_IntEn_ADDR:	0x1
BYTE			LED5_IntEn_ADDR;
#define LED5_MASK 0x20
// LED6 address and mask defines
#pragma	ioport	LED6_Data_ADDR:	0x0
BYTE			LED6_Data_ADDR;
#pragma	ioport	LED6_DriveMode_0_ADDR:	0x100
BYTE			LED6_DriveMode_0_ADDR;
#pragma	ioport	LED6_DriveMode_1_ADDR:	0x101
BYTE			LED6_DriveMode_1_ADDR;
#pragma	ioport	LED6_DriveMode_2_ADDR:	0x3
BYTE			LED6_DriveMode_2_ADDR;
#pragma	ioport	LED6_GlobalSelect_ADDR:	0x2
BYTE			LED6_GlobalSelect_ADDR;
#pragma	ioport	LED6_IntCtrl_0_ADDR:	0x102
BYTE			LED6_IntCtrl_0_ADDR;
#pragma	ioport	LED6_IntCtrl_1_ADDR:	0x103
BYTE			LED6_IntCtrl_1_ADDR;
#pragma	ioport	LED6_IntEn_ADDR:	0x1
BYTE			LED6_IntEn_ADDR;
#define LED6_MASK 0x40
// LED7 address and mask defines
#pragma	ioport	LED7_Data_ADDR:	0x0
BYTE			LED7_Data_ADDR;
#pragma	ioport	LED7_DriveMode_0_ADDR:	0x100
BYTE			LED7_DriveMode_0_ADDR;
#pragma	ioport	LED7_DriveMode_1_ADDR:	0x101
BYTE			LED7_DriveMode_1_ADDR;
#pragma	ioport	LED7_DriveMode_2_ADDR:	0x3
BYTE			LED7_DriveMode_2_ADDR;
#pragma	ioport	LED7_GlobalSelect_ADDR:	0x2
BYTE			LED7_GlobalSelect_ADDR;
#pragma	ioport	LED7_IntCtrl_0_ADDR:	0x102
BYTE			LED7_IntCtrl_0_ADDR;
#pragma	ioport	LED7_IntCtrl_1_ADDR:	0x103
BYTE			LED7_IntCtrl_1_ADDR;
#pragma	ioport	LED7_IntEn_ADDR:	0x1
BYTE			LED7_IntEn_ADDR;
#define LED7_MASK 0x80
