PROJNAME=ps2bitbang
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=Z:/DOCUME~1/ECE_381/PS2BIT~1/PS2BIT~1
PSOCDIR=C:/PROGRA~1/Cypress/PSOCDE~1/5.4/Common/CY3E64~1
INCLUDE_PATH=C:/PROGRA~1/Cypress/PSOCDE~1/5.4/Common/CY3E64~1/tools/include/CY8C29~1
CSRCS= keyboard.c main.c mouse.c ps2.c
LIBCSRCS=
STDCSRCS=
ASMSRCS=
LIBASMSRCS= lcd.asm ps2digbuf.asm ps2digbufint.asm ps2oneshot.asm ps2oneshotint.asm psocconfig.asm psocconfigtbl.asm pwm8led.asm pwm8ledint.asm pwmpiano1.asm pwmpiano1int.asm pwmpiano2.asm pwmpiano2int.asm pwmpiano3.asm pwmpiano3int.asm tenmicrosectimer.asm tenmicrosectimerint.asm uart.asm uartclock.asm uartclockint.asm uartint.asm uartplus.asm
STDASMSRCS=
OBJECT_SOURCES= keyboard.c main.c mouse.c ps2.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=ps2bitbang 
