//*****************************************************************************
//*****************************************************************************
//  FILENAME: PS2CLKBuf.h
//  Version: 1.3, Updated on 2010/9/19 at 23:40:30
//  Generated by PSoC Designer 5.1.1875.0
//
//  DESCRIPTION: DigitalBuffers User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PS2CLKBuf_INCLUDE
#define PS2CLKBuf_INCLUDE

#include <m8c.h>

#pragma fastcall16 PS2CLKBuf_EnableInt
#pragma fastcall16 PS2CLKBuf_DisableInt
#pragma fastcall16 PS2CLKBuf_Start
#pragma fastcall16 PS2CLKBuf_Stop

//-------------------------------------------------
// Prototypes of the PS2CLKBuf API.
//-------------------------------------------------

extern void PS2CLKBuf_EnableInt(void);
extern void PS2CLKBuf_DisableInt(void);
extern void PS2CLKBuf_Start(void);
extern void PS2CLKBuf_Stop(void);


//--------------------------------------------------
// Constants for PS2CLKBuf API's.
//--------------------------------------------------
#define PS2CLKBuf_CONTROL_REG_START_BIT        ( 0x01 )
#define PS2CLKBuf_INT_REG_ADDR                 ( 0x0df )
#define PS2CLKBuf_INT_MASK                     ( 0x10 )


//--------------------------------------------------
// Constants for PS2CLKBuf user defined values
//--------------------------------------------------
#pragma ioport  PS2CLKBuf_DATA_0_REG:   0x050              //DR0 Count register
BYTE            PS2CLKBuf_DATA_0_REG;
#pragma ioport  PS2CLKBuf_DATA_1_REG:   0x051              //DR1 Period register
BYTE            PS2CLKBuf_DATA_1_REG;
#pragma ioport  PS2CLKBuf_DATA_2_REG:   0x052              //DR2 Compare register
BYTE            PS2CLKBuf_DATA_2_REG;
#pragma ioport  PS2CLKBuf_CONTROL_REG:  0x053              //Control register
BYTE            PS2CLKBuf_CONTROL_REG;
#pragma ioport  PS2CLKBuf_FUNC_REG: 0x150                  //Function register
BYTE            PS2CLKBuf_FUNC_REG;
#pragma ioport  PS2CLKBuf_INPUT_REG:    0x151              //Input register
BYTE            PS2CLKBuf_INPUT_REG;
#pragma ioport  PS2CLKBuf_OUTPUT_REG:   0x152              //Output register
BYTE            PS2CLKBuf_OUTPUT_REG;
#pragma ioport  PS2CLKBuf_INT_REG:       0x0df             //Interrupt Mask Register
BYTE            PS2CLKBuf_INT_REG;


//-------------------------------------------------
// Register Addresses for PS2CLKBuf
//-------------------------------------------------


//-------------------------------------------------
// PS2CLKBuf Macro 'Functions'
//-------------------------------------------------

#define PS2CLKBuf_Start_M \
   PS2CLKBuf_CONTROL_REG |=  PS2CLKBuf_CONTROL_REG_START_BIT

#define PS2CLKBuf_Stop_M  \
   PS2CLKBuf_CONTROL_REG &= ~PS2CLKBuf_CONTROL_REG_START_BIT

#define PS2CLKBuf_EnableInt_M   \
   M8C_EnableIntMask(PS2CLKBuf_INT_REG, PS2CLKBuf_INT_MASK)

#define PS2CLKBuf_DisableInt_M  \
   M8C_DisableIntMask(PS2CLKBuf_INT_REG, PS2CLKBuf_INT_MASK)

#endif
// end of file PS2CLKBuf.h
