//*****************************************************************************
//*****************************************************************************
//  FILENAME: PS2DigBuf.h
//  Version: 1.3, Updated on 2013/5/19 at 10:43:26
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: DigitalBuffers User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PS2DigBuf_INCLUDE
#define PS2DigBuf_INCLUDE

#include <m8c.h>

#pragma fastcall16 PS2DigBuf_EnableInt
#pragma fastcall16 PS2DigBuf_DisableInt
#pragma fastcall16 PS2DigBuf_Start
#pragma fastcall16 PS2DigBuf_Stop

//-------------------------------------------------
// Prototypes of the PS2DigBuf API.
//-------------------------------------------------

extern void PS2DigBuf_EnableInt(void);
extern void PS2DigBuf_DisableInt(void);
extern void PS2DigBuf_Start(void);
extern void PS2DigBuf_Stop(void);


//--------------------------------------------------
// Constants for PS2DigBuf API's.
//--------------------------------------------------
#define PS2DigBuf_CONTROL_REG_START_BIT        ( 0x01 )
#define PS2DigBuf_INT_REG_ADDR                 ( 0x0e1 )
#define PS2DigBuf_INT_MASK                     ( 0x10 )


//--------------------------------------------------
// Constants for PS2DigBuf user defined values
//--------------------------------------------------
#pragma ioport  PS2DigBuf_DATA_0_REG:   0x030              //DR0 Count register
BYTE            PS2DigBuf_DATA_0_REG;
#pragma ioport  PS2DigBuf_DATA_1_REG:   0x031              //DR1 Period register
BYTE            PS2DigBuf_DATA_1_REG;
#pragma ioport  PS2DigBuf_DATA_2_REG:   0x032              //DR2 Compare register
BYTE            PS2DigBuf_DATA_2_REG;
#pragma ioport  PS2DigBuf_CONTROL_REG:  0x033              //Control register
BYTE            PS2DigBuf_CONTROL_REG;
#pragma ioport  PS2DigBuf_FUNC_REG: 0x130                  //Function register
BYTE            PS2DigBuf_FUNC_REG;
#pragma ioport  PS2DigBuf_INPUT_REG:    0x131              //Input register
BYTE            PS2DigBuf_INPUT_REG;
#pragma ioport  PS2DigBuf_OUTPUT_REG:   0x132              //Output register
BYTE            PS2DigBuf_OUTPUT_REG;
#pragma ioport  PS2DigBuf_INT_REG:       0x0e1             //Interrupt Mask Register
BYTE            PS2DigBuf_INT_REG;


//-------------------------------------------------
// Register Addresses for PS2DigBuf
//-------------------------------------------------


//-------------------------------------------------
// PS2DigBuf Macro 'Functions'
//-------------------------------------------------

#define PS2DigBuf_Start_M \
   PS2DigBuf_CONTROL_REG |=  PS2DigBuf_CONTROL_REG_START_BIT

#define PS2DigBuf_Stop_M  \
   PS2DigBuf_CONTROL_REG &= ~PS2DigBuf_CONTROL_REG_START_BIT

#define PS2DigBuf_EnableInt_M   \
   M8C_EnableIntMask(PS2DigBuf_INT_REG, PS2DigBuf_INT_MASK)

#define PS2DigBuf_DisableInt_M  \
   M8C_DisableIntMask(PS2DigBuf_INT_REG, PS2DigBuf_INT_MASK)

#endif
// end of file PS2DigBuf.h
