//*****************************************************************************
//*****************************************************************************
//  FILENAME: PS2OneShot.h
//  Version: 1.0, Updated on 2013/5/19 at 10:43:57
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: OneShot8 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PS2OneShot_INCLUDE
#define PS2OneShot_INCLUDE

#include <m8c.h>

#pragma fastcall16  PS2OneShot_Start
#pragma fastcall16  PS2OneShot_Stop
#pragma fastcall16  PS2OneShot_EnableInt
#pragma fastcall16  PS2OneShot_DisableInt
#pragma fastcall16  PS2OneShot_ClearInt

#define PS2OneShot_INT_REG                  0x0e1
#define PS2OneShot_INT_MASK                 0x20

//-------------------------------------------------
// Prototypes of the PS2OneShot API.
//-------------------------------------------------
extern void  PS2OneShot_Start(void);
extern void  PS2OneShot_Stop(void);
extern void  PS2OneShot_EnableInt(void);
extern void  PS2OneShot_DisableInt(void);
extern void  PS2OneShot_ClearInt(void);

//-------------------------------------------------
// Register Addresses for PS2OneShot
//-------------------------------------------------
#pragma ioport  PS2OneShot_FUNC_REG:    0x134              //Function register LSB
BYTE            PS2OneShot_FUNC_REG;
#pragma ioport  PS2OneShot_INPUT_REG:   0x135              //Input register LSB
BYTE            PS2OneShot_INPUT_REG;
#pragma ioport  PS2OneShot_OUTPUT_REG:  0x136              //Output register LSB
BYTE            PS2OneShot_OUTPUT_REG;
#pragma ioport  PS2OneShot_CONTROL_REG: 0x037              //Control register LSB
BYTE            PS2OneShot_CONTROL_REG;
#pragma ioport  PS2OneShot_SHIFT_REG:   0x034              //Shift register LSB
BYTE            PS2OneShot_SHIFT_REG;
#pragma ioport  PS2OneShot_POLY_REG:    0x035              //Polynomial register LSB
BYTE            PS2OneShot_POLY_REG;
#pragma ioport  PS2OneShot_SEED_REG:    0x036              //Seed register LSB
BYTE            PS2OneShot_SEED_REG;

#endif
// end of file PS2OneShot.h
