/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// PWMPiano1_OUT address and mask defines
#pragma	ioport	PWMPiano1_OUT_Data_ADDR:	0x0
BYTE			PWMPiano1_OUT_Data_ADDR;
#pragma	ioport	PWMPiano1_OUT_DriveMode_0_ADDR:	0x100
BYTE			PWMPiano1_OUT_DriveMode_0_ADDR;
#pragma	ioport	PWMPiano1_OUT_DriveMode_1_ADDR:	0x101
BYTE			PWMPiano1_OUT_DriveMode_1_ADDR;
#pragma	ioport	PWMPiano1_OUT_DriveMode_2_ADDR:	0x3
BYTE			PWMPiano1_OUT_DriveMode_2_ADDR;
#pragma	ioport	PWMPiano1_OUT_GlobalSelect_ADDR:	0x2
BYTE			PWMPiano1_OUT_GlobalSelect_ADDR;
#pragma	ioport	PWMPiano1_OUT_IntCtrl_0_ADDR:	0x102
BYTE			PWMPiano1_OUT_IntCtrl_0_ADDR;
#pragma	ioport	PWMPiano1_OUT_IntCtrl_1_ADDR:	0x103
BYTE			PWMPiano1_OUT_IntCtrl_1_ADDR;
#pragma	ioport	PWMPiano1_OUT_IntEn_ADDR:	0x1
BYTE			PWMPiano1_OUT_IntEn_ADDR;
#define PWMPiano1_OUT_MASK 0x1
// PWMPiano2_OUT address and mask defines
#pragma	ioport	PWMPiano2_OUT_Data_ADDR:	0x0
BYTE			PWMPiano2_OUT_Data_ADDR;
#pragma	ioport	PWMPiano2_OUT_DriveMode_0_ADDR:	0x100
BYTE			PWMPiano2_OUT_DriveMode_0_ADDR;
#pragma	ioport	PWMPiano2_OUT_DriveMode_1_ADDR:	0x101
BYTE			PWMPiano2_OUT_DriveMode_1_ADDR;
#pragma	ioport	PWMPiano2_OUT_DriveMode_2_ADDR:	0x3
BYTE			PWMPiano2_OUT_DriveMode_2_ADDR;
#pragma	ioport	PWMPiano2_OUT_GlobalSelect_ADDR:	0x2
BYTE			PWMPiano2_OUT_GlobalSelect_ADDR;
#pragma	ioport	PWMPiano2_OUT_IntCtrl_0_ADDR:	0x102
BYTE			PWMPiano2_OUT_IntCtrl_0_ADDR;
#pragma	ioport	PWMPiano2_OUT_IntCtrl_1_ADDR:	0x103
BYTE			PWMPiano2_OUT_IntCtrl_1_ADDR;
#pragma	ioport	PWMPiano2_OUT_IntEn_ADDR:	0x1
BYTE			PWMPiano2_OUT_IntEn_ADDR;
#define PWMPiano2_OUT_MASK 0x2
// PWMPiano3_OUT address and mask defines
#pragma	ioport	PWMPiano3_OUT_Data_ADDR:	0x0
BYTE			PWMPiano3_OUT_Data_ADDR;
#pragma	ioport	PWMPiano3_OUT_DriveMode_0_ADDR:	0x100
BYTE			PWMPiano3_OUT_DriveMode_0_ADDR;
#pragma	ioport	PWMPiano3_OUT_DriveMode_1_ADDR:	0x101
BYTE			PWMPiano3_OUT_DriveMode_1_ADDR;
#pragma	ioport	PWMPiano3_OUT_DriveMode_2_ADDR:	0x3
BYTE			PWMPiano3_OUT_DriveMode_2_ADDR;
#pragma	ioport	PWMPiano3_OUT_GlobalSelect_ADDR:	0x2
BYTE			PWMPiano3_OUT_GlobalSelect_ADDR;
#pragma	ioport	PWMPiano3_OUT_IntCtrl_0_ADDR:	0x102
BYTE			PWMPiano3_OUT_IntCtrl_0_ADDR;
#pragma	ioport	PWMPiano3_OUT_IntCtrl_1_ADDR:	0x103
BYTE			PWMPiano3_OUT_IntCtrl_1_ADDR;
#pragma	ioport	PWMPiano3_OUT_IntEn_ADDR:	0x1
BYTE			PWMPiano3_OUT_IntEn_ADDR;
#define PWMPiano3_OUT_MASK 0x4
// LED1 address and mask defines
#pragma	ioport	LED1_Data_ADDR:	0x4
BYTE			LED1_Data_ADDR;
#pragma	ioport	LED1_DriveMode_0_ADDR:	0x104
BYTE			LED1_DriveMode_0_ADDR;
#pragma	ioport	LED1_DriveMode_1_ADDR:	0x105
BYTE			LED1_DriveMode_1_ADDR;
#pragma	ioport	LED1_DriveMode_2_ADDR:	0x7
BYTE			LED1_DriveMode_2_ADDR;
#pragma	ioport	LED1_GlobalSelect_ADDR:	0x6
BYTE			LED1_GlobalSelect_ADDR;
#pragma	ioport	LED1_IntCtrl_0_ADDR:	0x106
BYTE			LED1_IntCtrl_0_ADDR;
#pragma	ioport	LED1_IntCtrl_1_ADDR:	0x107
BYTE			LED1_IntCtrl_1_ADDR;
#pragma	ioport	LED1_IntEn_ADDR:	0x5
BYTE			LED1_IntEn_ADDR;
#define LED1_MASK 0x1
// LED1 Shadow defines
//   LED1_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED1_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// PWM_LED address and mask defines
#pragma	ioport	PWM_LED_Data_ADDR:	0x4
BYTE			PWM_LED_Data_ADDR;
#pragma	ioport	PWM_LED_DriveMode_0_ADDR:	0x104
BYTE			PWM_LED_DriveMode_0_ADDR;
#pragma	ioport	PWM_LED_DriveMode_1_ADDR:	0x105
BYTE			PWM_LED_DriveMode_1_ADDR;
#pragma	ioport	PWM_LED_DriveMode_2_ADDR:	0x7
BYTE			PWM_LED_DriveMode_2_ADDR;
#pragma	ioport	PWM_LED_GlobalSelect_ADDR:	0x6
BYTE			PWM_LED_GlobalSelect_ADDR;
#pragma	ioport	PWM_LED_IntCtrl_0_ADDR:	0x106
BYTE			PWM_LED_IntCtrl_0_ADDR;
#pragma	ioport	PWM_LED_IntCtrl_1_ADDR:	0x107
BYTE			PWM_LED_IntCtrl_1_ADDR;
#pragma	ioport	PWM_LED_IntEn_ADDR:	0x5
BYTE			PWM_LED_IntEn_ADDR;
#define PWM_LED_MASK 0x2
// PWM_LED Shadow defines
//   PWM_LED_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define PWM_LED_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// PS2CLOCK_IN address and mask defines
#pragma	ioport	PS2CLOCK_IN_Data_ADDR:	0x4
BYTE			PS2CLOCK_IN_Data_ADDR;
#pragma	ioport	PS2CLOCK_IN_DriveMode_0_ADDR:	0x104
BYTE			PS2CLOCK_IN_DriveMode_0_ADDR;
#pragma	ioport	PS2CLOCK_IN_DriveMode_1_ADDR:	0x105
BYTE			PS2CLOCK_IN_DriveMode_1_ADDR;
#pragma	ioport	PS2CLOCK_IN_DriveMode_2_ADDR:	0x7
BYTE			PS2CLOCK_IN_DriveMode_2_ADDR;
#pragma	ioport	PS2CLOCK_IN_GlobalSelect_ADDR:	0x6
BYTE			PS2CLOCK_IN_GlobalSelect_ADDR;
#pragma	ioport	PS2CLOCK_IN_IntCtrl_0_ADDR:	0x106
BYTE			PS2CLOCK_IN_IntCtrl_0_ADDR;
#pragma	ioport	PS2CLOCK_IN_IntCtrl_1_ADDR:	0x107
BYTE			PS2CLOCK_IN_IntCtrl_1_ADDR;
#pragma	ioport	PS2CLOCK_IN_IntEn_ADDR:	0x5
BYTE			PS2CLOCK_IN_IntEn_ADDR;
#define PS2CLOCK_IN_MASK 0x4
// PS2CLOCK_IN Shadow defines
//   PS2CLOCK_IN_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define PS2CLOCK_IN_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// PS2CLOCK address and mask defines
#pragma	ioport	PS2CLOCK_Data_ADDR:	0x4
BYTE			PS2CLOCK_Data_ADDR;
#pragma	ioport	PS2CLOCK_DriveMode_0_ADDR:	0x104
BYTE			PS2CLOCK_DriveMode_0_ADDR;
#pragma	ioport	PS2CLOCK_DriveMode_1_ADDR:	0x105
BYTE			PS2CLOCK_DriveMode_1_ADDR;
#pragma	ioport	PS2CLOCK_DriveMode_2_ADDR:	0x7
BYTE			PS2CLOCK_DriveMode_2_ADDR;
#pragma	ioport	PS2CLOCK_GlobalSelect_ADDR:	0x6
BYTE			PS2CLOCK_GlobalSelect_ADDR;
#pragma	ioport	PS2CLOCK_IntCtrl_0_ADDR:	0x106
BYTE			PS2CLOCK_IntCtrl_0_ADDR;
#pragma	ioport	PS2CLOCK_IntCtrl_1_ADDR:	0x107
BYTE			PS2CLOCK_IntCtrl_1_ADDR;
#pragma	ioport	PS2CLOCK_IntEn_ADDR:	0x5
BYTE			PS2CLOCK_IntEn_ADDR;
#define PS2CLOCK_MASK 0x8
// PS2CLOCK Shadow defines
//   PS2CLOCK_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define PS2CLOCK_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// PS2DATA address and mask defines
#pragma	ioport	PS2DATA_Data_ADDR:	0x4
BYTE			PS2DATA_Data_ADDR;
#pragma	ioport	PS2DATA_DriveMode_0_ADDR:	0x104
BYTE			PS2DATA_DriveMode_0_ADDR;
#pragma	ioport	PS2DATA_DriveMode_1_ADDR:	0x105
BYTE			PS2DATA_DriveMode_1_ADDR;
#pragma	ioport	PS2DATA_DriveMode_2_ADDR:	0x7
BYTE			PS2DATA_DriveMode_2_ADDR;
#pragma	ioport	PS2DATA_GlobalSelect_ADDR:	0x6
BYTE			PS2DATA_GlobalSelect_ADDR;
#pragma	ioport	PS2DATA_IntCtrl_0_ADDR:	0x106
BYTE			PS2DATA_IntCtrl_0_ADDR;
#pragma	ioport	PS2DATA_IntCtrl_1_ADDR:	0x107
BYTE			PS2DATA_IntCtrl_1_ADDR;
#pragma	ioport	PS2DATA_IntEn_ADDR:	0x5
BYTE			PS2DATA_IntEn_ADDR;
#define PS2DATA_MASK 0x10
// PS2DATA Shadow defines
//   PS2DATA_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define PS2DATA_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// TRIGGER address and mask defines
#pragma	ioport	TRIGGER_Data_ADDR:	0x4
BYTE			TRIGGER_Data_ADDR;
#pragma	ioport	TRIGGER_DriveMode_0_ADDR:	0x104
BYTE			TRIGGER_DriveMode_0_ADDR;
#pragma	ioport	TRIGGER_DriveMode_1_ADDR:	0x105
BYTE			TRIGGER_DriveMode_1_ADDR;
#pragma	ioport	TRIGGER_DriveMode_2_ADDR:	0x7
BYTE			TRIGGER_DriveMode_2_ADDR;
#pragma	ioport	TRIGGER_GlobalSelect_ADDR:	0x6
BYTE			TRIGGER_GlobalSelect_ADDR;
#pragma	ioport	TRIGGER_IntCtrl_0_ADDR:	0x106
BYTE			TRIGGER_IntCtrl_0_ADDR;
#pragma	ioport	TRIGGER_IntCtrl_1_ADDR:	0x107
BYTE			TRIGGER_IntCtrl_1_ADDR;
#pragma	ioport	TRIGGER_IntEn_ADDR:	0x5
BYTE			TRIGGER_IntEn_ADDR;
#define TRIGGER_MASK 0x20
// TRIGGER Shadow defines
//   TRIGGER_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define TRIGGER_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// UART_RX address and mask defines
#pragma	ioport	UART_RX_Data_ADDR:	0x4
BYTE			UART_RX_Data_ADDR;
#pragma	ioport	UART_RX_DriveMode_0_ADDR:	0x104
BYTE			UART_RX_DriveMode_0_ADDR;
#pragma	ioport	UART_RX_DriveMode_1_ADDR:	0x105
BYTE			UART_RX_DriveMode_1_ADDR;
#pragma	ioport	UART_RX_DriveMode_2_ADDR:	0x7
BYTE			UART_RX_DriveMode_2_ADDR;
#pragma	ioport	UART_RX_GlobalSelect_ADDR:	0x6
BYTE			UART_RX_GlobalSelect_ADDR;
#pragma	ioport	UART_RX_IntCtrl_0_ADDR:	0x106
BYTE			UART_RX_IntCtrl_0_ADDR;
#pragma	ioport	UART_RX_IntCtrl_1_ADDR:	0x107
BYTE			UART_RX_IntCtrl_1_ADDR;
#pragma	ioport	UART_RX_IntEn_ADDR:	0x5
BYTE			UART_RX_IntEn_ADDR;
#define UART_RX_MASK 0x40
// UART_RX Shadow defines
//   UART_RX_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define UART_RX_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LCDD4 address and mask defines
#pragma	ioport	LCDD4_Data_ADDR:	0x8
BYTE			LCDD4_Data_ADDR;
#pragma	ioport	LCDD4_DriveMode_0_ADDR:	0x108
BYTE			LCDD4_DriveMode_0_ADDR;
#pragma	ioport	LCDD4_DriveMode_1_ADDR:	0x109
BYTE			LCDD4_DriveMode_1_ADDR;
#pragma	ioport	LCDD4_DriveMode_2_ADDR:	0xb
BYTE			LCDD4_DriveMode_2_ADDR;
#pragma	ioport	LCDD4_GlobalSelect_ADDR:	0xa
BYTE			LCDD4_GlobalSelect_ADDR;
#pragma	ioport	LCDD4_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD4_IntCtrl_0_ADDR;
#pragma	ioport	LCDD4_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD4_IntCtrl_1_ADDR;
#pragma	ioport	LCDD4_IntEn_ADDR:	0x9
BYTE			LCDD4_IntEn_ADDR;
#define LCDD4_MASK 0x1
// LCDD4 Shadow defines
//   LCDD4_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD4_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD4_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD4_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD4_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD4_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD5 address and mask defines
#pragma	ioport	LCDD5_Data_ADDR:	0x8
BYTE			LCDD5_Data_ADDR;
#pragma	ioport	LCDD5_DriveMode_0_ADDR:	0x108
BYTE			LCDD5_DriveMode_0_ADDR;
#pragma	ioport	LCDD5_DriveMode_1_ADDR:	0x109
BYTE			LCDD5_DriveMode_1_ADDR;
#pragma	ioport	LCDD5_DriveMode_2_ADDR:	0xb
BYTE			LCDD5_DriveMode_2_ADDR;
#pragma	ioport	LCDD5_GlobalSelect_ADDR:	0xa
BYTE			LCDD5_GlobalSelect_ADDR;
#pragma	ioport	LCDD5_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD5_IntCtrl_0_ADDR;
#pragma	ioport	LCDD5_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD5_IntCtrl_1_ADDR;
#pragma	ioport	LCDD5_IntEn_ADDR:	0x9
BYTE			LCDD5_IntEn_ADDR;
#define LCDD5_MASK 0x2
// LCDD5 Shadow defines
//   LCDD5_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD5_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD5_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD5_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD5_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD5_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD6 address and mask defines
#pragma	ioport	LCDD6_Data_ADDR:	0x8
BYTE			LCDD6_Data_ADDR;
#pragma	ioport	LCDD6_DriveMode_0_ADDR:	0x108
BYTE			LCDD6_DriveMode_0_ADDR;
#pragma	ioport	LCDD6_DriveMode_1_ADDR:	0x109
BYTE			LCDD6_DriveMode_1_ADDR;
#pragma	ioport	LCDD6_DriveMode_2_ADDR:	0xb
BYTE			LCDD6_DriveMode_2_ADDR;
#pragma	ioport	LCDD6_GlobalSelect_ADDR:	0xa
BYTE			LCDD6_GlobalSelect_ADDR;
#pragma	ioport	LCDD6_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD6_IntCtrl_0_ADDR;
#pragma	ioport	LCDD6_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD6_IntCtrl_1_ADDR;
#pragma	ioport	LCDD6_IntEn_ADDR:	0x9
BYTE			LCDD6_IntEn_ADDR;
#define LCDD6_MASK 0x4
// LCDD6 Shadow defines
//   LCDD6_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD6_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD6_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD6_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD6_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD6_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD7 address and mask defines
#pragma	ioport	LCDD7_Data_ADDR:	0x8
BYTE			LCDD7_Data_ADDR;
#pragma	ioport	LCDD7_DriveMode_0_ADDR:	0x108
BYTE			LCDD7_DriveMode_0_ADDR;
#pragma	ioport	LCDD7_DriveMode_1_ADDR:	0x109
BYTE			LCDD7_DriveMode_1_ADDR;
#pragma	ioport	LCDD7_DriveMode_2_ADDR:	0xb
BYTE			LCDD7_DriveMode_2_ADDR;
#pragma	ioport	LCDD7_GlobalSelect_ADDR:	0xa
BYTE			LCDD7_GlobalSelect_ADDR;
#pragma	ioport	LCDD7_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD7_IntCtrl_0_ADDR;
#pragma	ioport	LCDD7_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD7_IntCtrl_1_ADDR;
#pragma	ioport	LCDD7_IntEn_ADDR:	0x9
BYTE			LCDD7_IntEn_ADDR;
#define LCDD7_MASK 0x8
// LCDD7 Shadow defines
//   LCDD7_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD7_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD7_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD7_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD7_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD7_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDE address and mask defines
#pragma	ioport	LCDE_Data_ADDR:	0x8
BYTE			LCDE_Data_ADDR;
#pragma	ioport	LCDE_DriveMode_0_ADDR:	0x108
BYTE			LCDE_DriveMode_0_ADDR;
#pragma	ioport	LCDE_DriveMode_1_ADDR:	0x109
BYTE			LCDE_DriveMode_1_ADDR;
#pragma	ioport	LCDE_DriveMode_2_ADDR:	0xb
BYTE			LCDE_DriveMode_2_ADDR;
#pragma	ioport	LCDE_GlobalSelect_ADDR:	0xa
BYTE			LCDE_GlobalSelect_ADDR;
#pragma	ioport	LCDE_IntCtrl_0_ADDR:	0x10a
BYTE			LCDE_IntCtrl_0_ADDR;
#pragma	ioport	LCDE_IntCtrl_1_ADDR:	0x10b
BYTE			LCDE_IntCtrl_1_ADDR;
#pragma	ioport	LCDE_IntEn_ADDR:	0x9
BYTE			LCDE_IntEn_ADDR;
#define LCDE_MASK 0x10
// LCDE Shadow defines
//   LCDE_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDE_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDE_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDE_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDE_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDE_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDRS address and mask defines
#pragma	ioport	LCDRS_Data_ADDR:	0x8
BYTE			LCDRS_Data_ADDR;
#pragma	ioport	LCDRS_DriveMode_0_ADDR:	0x108
BYTE			LCDRS_DriveMode_0_ADDR;
#pragma	ioport	LCDRS_DriveMode_1_ADDR:	0x109
BYTE			LCDRS_DriveMode_1_ADDR;
#pragma	ioport	LCDRS_DriveMode_2_ADDR:	0xb
BYTE			LCDRS_DriveMode_2_ADDR;
#pragma	ioport	LCDRS_GlobalSelect_ADDR:	0xa
BYTE			LCDRS_GlobalSelect_ADDR;
#pragma	ioport	LCDRS_IntCtrl_0_ADDR:	0x10a
BYTE			LCDRS_IntCtrl_0_ADDR;
#pragma	ioport	LCDRS_IntCtrl_1_ADDR:	0x10b
BYTE			LCDRS_IntCtrl_1_ADDR;
#pragma	ioport	LCDRS_IntEn_ADDR:	0x9
BYTE			LCDRS_IntEn_ADDR;
#define LCDRS_MASK 0x20
// LCDRS Shadow defines
//   LCDRS_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDRS_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDRS_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDRS_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDRS_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDRS_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDRW address and mask defines
#pragma	ioport	LCDRW_Data_ADDR:	0x8
BYTE			LCDRW_Data_ADDR;
#pragma	ioport	LCDRW_DriveMode_0_ADDR:	0x108
BYTE			LCDRW_DriveMode_0_ADDR;
#pragma	ioport	LCDRW_DriveMode_1_ADDR:	0x109
BYTE			LCDRW_DriveMode_1_ADDR;
#pragma	ioport	LCDRW_DriveMode_2_ADDR:	0xb
BYTE			LCDRW_DriveMode_2_ADDR;
#pragma	ioport	LCDRW_GlobalSelect_ADDR:	0xa
BYTE			LCDRW_GlobalSelect_ADDR;
#pragma	ioport	LCDRW_IntCtrl_0_ADDR:	0x10a
BYTE			LCDRW_IntCtrl_0_ADDR;
#pragma	ioport	LCDRW_IntCtrl_1_ADDR:	0x10b
BYTE			LCDRW_IntCtrl_1_ADDR;
#pragma	ioport	LCDRW_IntEn_ADDR:	0x9
BYTE			LCDRW_IntEn_ADDR;
#define LCDRW_MASK 0x40
// LCDRW Shadow defines
//   LCDRW_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDRW_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDRW_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDRW_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDRW_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDRW_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// UART_TX address and mask defines
#pragma	ioport	UART_TX_Data_ADDR:	0x8
BYTE			UART_TX_Data_ADDR;
#pragma	ioport	UART_TX_DriveMode_0_ADDR:	0x108
BYTE			UART_TX_DriveMode_0_ADDR;
#pragma	ioport	UART_TX_DriveMode_1_ADDR:	0x109
BYTE			UART_TX_DriveMode_1_ADDR;
#pragma	ioport	UART_TX_DriveMode_2_ADDR:	0xb
BYTE			UART_TX_DriveMode_2_ADDR;
#pragma	ioport	UART_TX_GlobalSelect_ADDR:	0xa
BYTE			UART_TX_GlobalSelect_ADDR;
#pragma	ioport	UART_TX_IntCtrl_0_ADDR:	0x10a
BYTE			UART_TX_IntCtrl_0_ADDR;
#pragma	ioport	UART_TX_IntCtrl_1_ADDR:	0x10b
BYTE			UART_TX_IntCtrl_1_ADDR;
#pragma	ioport	UART_TX_IntEn_ADDR:	0x9
BYTE			UART_TX_IntEn_ADDR;
#define UART_TX_MASK 0x80
// UART_TX Shadow defines
//   UART_TX_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define UART_TX_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   UART_TX_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define UART_TX_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   UART_TX_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define UART_TX_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
