//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWMPiano2.h
//   Version: 2.5, Updated on 2013/5/19 at 10:44:6
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWMPiano2_INCLUDE
#define PWMPiano2_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWMPiano2_EnableInt
#pragma fastcall16 PWMPiano2_DisableInt
#pragma fastcall16 PWMPiano2_Start
#pragma fastcall16 PWMPiano2_Stop
#pragma fastcall16 PWMPiano2_wReadCounter              // Read  DR0
#pragma fastcall16 PWMPiano2_WritePeriod               // Write DR1
#pragma fastcall16 PWMPiano2_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWMPiano2_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWMPiano2_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWMPiano2_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWMPiano2 API.
//-------------------------------------------------

extern void PWMPiano2_EnableInt(void);                  // Proxy Class 1
extern void PWMPiano2_DisableInt(void);                 // Proxy Class 1
extern void PWMPiano2_Start(void);                      // Proxy Class 1
extern void PWMPiano2_Stop(void);                       // Proxy Class 1
extern WORD PWMPiano2_wReadCounter(void);               // Proxy Class 2
extern void PWMPiano2_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWMPiano2_wReadPulseWidth(void);            // Proxy Class 1
extern void PWMPiano2_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWMPiano2_ReadCounter(void);            // Deprecated
extern WORD wPWMPiano2_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWMPiano2 API's.
//-------------------------------------------------

#define PWMPiano2_CONTROL_REG_START_BIT        ( 0x01 )
#define PWMPiano2_INT_REG_ADDR                 ( 0x0e1 )
#define PWMPiano2_INT_MASK                     ( 0x02 )


//--------------------------------------------------
// Constants for PWMPiano2 user defined values
//--------------------------------------------------

#define PWMPiano2_PERIOD                       ( 0x0 )
#define PWMPiano2_PULSE_WIDTH                  ( 0x0 )


//-------------------------------------------------
// Register Addresses for PWMPiano2
//-------------------------------------------------

#pragma ioport  PWMPiano2_COUNTER_LSB_REG:  0x020          //DR0 Count register LSB
BYTE            PWMPiano2_COUNTER_LSB_REG;
#pragma ioport  PWMPiano2_COUNTER_MSB_REG:  0x024          //DR0 Count register MSB
BYTE            PWMPiano2_COUNTER_MSB_REG;
#pragma ioport  PWMPiano2_PERIOD_LSB_REG:   0x021          //DR1 Period register LSB
BYTE            PWMPiano2_PERIOD_LSB_REG;
#pragma ioport  PWMPiano2_PERIOD_MSB_REG:   0x025          //DR1 Period register MSB
BYTE            PWMPiano2_PERIOD_MSB_REG;
#pragma ioport  PWMPiano2_COMPARE_LSB_REG:  0x022          //DR2 Compare register LSB
BYTE            PWMPiano2_COMPARE_LSB_REG;
#pragma ioport  PWMPiano2_COMPARE_MSB_REG:  0x026          //DR2 Compare register MSB
BYTE            PWMPiano2_COMPARE_MSB_REG;
#pragma ioport  PWMPiano2_CONTROL_LSB_REG:  0x023          //Control register LSB
BYTE            PWMPiano2_CONTROL_LSB_REG;
#pragma ioport  PWMPiano2_CONTROL_MSB_REG:  0x027          //Control register MSB
BYTE            PWMPiano2_CONTROL_MSB_REG;
#pragma ioport  PWMPiano2_FUNC_LSB_REG: 0x120              //Function register LSB
BYTE            PWMPiano2_FUNC_LSB_REG;
#pragma ioport  PWMPiano2_FUNC_MSB_REG: 0x124              //Function register MSB
BYTE            PWMPiano2_FUNC_MSB_REG;
#pragma ioport  PWMPiano2_INPUT_LSB_REG:    0x121          //Input register LSB
BYTE            PWMPiano2_INPUT_LSB_REG;
#pragma ioport  PWMPiano2_INPUT_MSB_REG:    0x125          //Input register MSB
BYTE            PWMPiano2_INPUT_MSB_REG;
#pragma ioport  PWMPiano2_OUTPUT_LSB_REG:   0x122          //Output register LSB
BYTE            PWMPiano2_OUTPUT_LSB_REG;
#pragma ioport  PWMPiano2_OUTPUT_MSB_REG:   0x126          //Output register MSB
BYTE            PWMPiano2_OUTPUT_MSB_REG;
#pragma ioport  PWMPiano2_INT_REG:       0x0e1             //Interrupt Mask Register
BYTE            PWMPiano2_INT_REG;


//-------------------------------------------------
// PWMPiano2 Macro 'Functions'
//-------------------------------------------------

#define PWMPiano2_Start_M \
   ( PWMPiano2_CONTROL_LSB_REG |=  PWMPiano2_CONTROL_REG_START_BIT )

#define PWMPiano2_Stop_M  \
   ( PWMPiano2_CONTROL_LSB_REG &= ~PWMPiano2_CONTROL_REG_START_BIT )

#define PWMPiano2_EnableInt_M   \
   M8C_EnableIntMask(  PWMPiano2_INT_REG, PWMPiano2_INT_MASK )

#define PWMPiano2_DisableInt_M  \
   M8C_DisableIntMask( PWMPiano2_INT_REG, PWMPiano2_INT_MASK )

#endif
// end of file PWMPiano2.h
