//*****************************************************************************
//*****************************************************************************
//  FILENAME: DelSigClock.h
//   Version: 2.60, Updated on 2015/3/4 at 22:23:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Counter8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef DelSigClock_INCLUDE
#define DelSigClock_INCLUDE

#include <m8c.h>

#pragma fastcall16 DelSigClock_EnableInt
#pragma fastcall16 DelSigClock_DisableInt
#pragma fastcall16 DelSigClock_Start
#pragma fastcall16 DelSigClock_Stop
#pragma fastcall16 DelSigClock_bReadCounter              // Read  DR0
#pragma fastcall16 DelSigClock_WritePeriod               // Write DR1
#pragma fastcall16 DelSigClock_bReadCompareValue         // Read  DR2
#pragma fastcall16 DelSigClock_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bDelSigClock_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bDelSigClock_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the DelSigClock API.
//-------------------------------------------------

extern void DelSigClock_EnableInt(void);                           // Proxy Class 1
extern void DelSigClock_DisableInt(void);                          // Proxy Class 1
extern void DelSigClock_Start(void);                               // Proxy Class 1
extern void DelSigClock_Stop(void);                                // Proxy Class 1
extern BYTE DelSigClock_bReadCounter(void);                        // Proxy Class 1
extern void DelSigClock_WritePeriod(BYTE bPeriod);                 // Proxy Class 1
extern BYTE DelSigClock_bReadCompareValue(void);                   // Proxy Class 2
extern void DelSigClock_WriteCompareValue(BYTE bCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bDelSigClock_ReadCounter(void);            // Deprecated
extern BYTE bDelSigClock_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for DelSigClock API's.
//--------------------------------------------------

#define DelSigClock_CONTROL_REG_START_BIT      ( 0x01 )
#define DelSigClock_INT_REG_ADDR               ( 0x0e1 )
#define DelSigClock_INT_MASK                   ( 0x08 )


//--------------------------------------------------
// Constants for DelSigClock user defined values
//--------------------------------------------------

#define DelSigClock_PERIOD                     ( 0x4a )
#define DelSigClock_COMPARE_VALUE              ( 0x25 )


//-------------------------------------------------
// Register Addresses for DelSigClock
//-------------------------------------------------

#pragma ioport  DelSigClock_COUNTER_REG:    0x02c          //DR0 Count register
BYTE            DelSigClock_COUNTER_REG;
#pragma ioport  DelSigClock_PERIOD_REG: 0x02d              //DR1 Period register
BYTE            DelSigClock_PERIOD_REG;
#pragma ioport  DelSigClock_COMPARE_REG:    0x02e          //DR2 Compare register
BYTE            DelSigClock_COMPARE_REG;
#pragma ioport  DelSigClock_CONTROL_REG:    0x02f          //Control register
BYTE            DelSigClock_CONTROL_REG;
#pragma ioport  DelSigClock_FUNC_REG:   0x12c              //Function register
BYTE            DelSigClock_FUNC_REG;
#pragma ioport  DelSigClock_INPUT_REG:  0x12d              //Input register
BYTE            DelSigClock_INPUT_REG;
#pragma ioport  DelSigClock_OUTPUT_REG: 0x12e              //Output register
BYTE            DelSigClock_OUTPUT_REG;
#pragma ioport  DelSigClock_INT_REG:       0x0e1           //Interrupt Mask Register
BYTE            DelSigClock_INT_REG;


//-------------------------------------------------
// DelSigClock Macro 'Functions'
//-------------------------------------------------

#define DelSigClock_Start_M \
   DelSigClock_CONTROL_REG |=  DelSigClock_CONTROL_REG_START_BIT

#define DelSigClock_Stop_M  \
   DelSigClock_CONTROL_REG &= ~DelSigClock_CONTROL_REG_START_BIT

#define DelSigClock_EnableInt_M   \
   M8C_EnableIntMask(DelSigClock_INT_REG, DelSigClock_INT_MASK)

#define DelSigClock_DisableInt_M  \
   M8C_DisableIntMask(DelSigClock_INT_REG, DelSigClock_INT_MASK)

#endif
// end of file DelSigClock.h
